version: '3.8'

services:
  comfystream:
    # Point to your context and Dockerfile
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    
    container_name: comfystream-dev

    # Configure any volumes/mounts for your workspace
    volumes:
      - ./workspace:/workspace
      - ./app:/app
      # Add more mounts if needed

    # Expose/forward the ports that ComfyUI and ComfyStream need
    ports:
      - "8188:8188"
      - "8889:8889"
      - "3000:3000"

    # Override the default CMD with your custom script
    command: [ "bash", "/app/init_or_start.sh" ]
    
    # Pass environment variables if you want
    environment:
      TWILIO_ACCOUNT_SID: "YOUR_ACCOUNT_SID_HERE"
      TWILIO_AUTH_TOKEN: "YOUR_AUTH_TOKEN_HERE" 